### ISSUE TITLE
Migrate Icons to React Icons

### ISSUE THREAD

**Issue by JosueBrenes** [safetrustcr/Frontend#132] opened 2024-12-14 02:18 UTC
# Migrate Icons to React Icons

## Description

Replace the following image files with equivalent icons from React Icons:

- `Frontend\public\img\Icon.svg`
- `Frontend\public\img\icon1.jpg`
- `Frontend\public\img\icon2.jpg`

Update the corresponding components to use React Icons instead of the image files.

## Migration Details

- **`Icon.svg`** should be replaced in the following locations:
  - `Frontend\src\components\auth\NewPassword\PasswordHeader.tsx`
  - `Frontend\src\components\auth\ForgotPassword\ForgotPasswordCard.tsx`

- **`icon1.jpg`** (image 1) should be replaced with a React Icon equivalent in:
  - `Frontend\src\components\bids\ProcessTimeline\index.tsx`

- **`icon2.jpg`** (image 2) should be replaced with a React Icon equivalent in:
  - `Frontend\src\components\bids\ProcessTimeline\index.tsx`

## Steps to Complete

1. Identify suitable React Icons to replace `Icon.svg`, `icon1.jpg` (image 1), and `icon2.jpg` (image 2).
2. Import the selected React Icons into the specified files.
3. Replace the image references with the imported React Icons.
4. Ensure the new icons are styled appropriately to match the original design.
5. Test all updated components to confirm proper functionality and appearance.
6. Commit and push the changes to the repository.

## Acceptance Criteria

- [ ] `Icon.svg`, `icon1.jpg`, and `icon2.jpg` are successfully replaced with React Icons.
- [ ] The specified components are updated to use React Icons instead of the image files.
- [ ] The new icons are styled correctly and match the original design.
- [ ] No errors or visual inconsistencies are present after the migration.

**Comment by GideonBature** [comment] 2024-12-14 02:47
I'd love to give this a go.

**Comment by SimplementeCao** [comment] 2024-12-14 02:53
---

### Hello! I'm *SimplementeCao* 👋

I have previously contributed to several projects, including:

- `Cairo Book`
- `Starknet Book`
- `Starknet Docs`
- `Starknet Security Challenges Factory`
- `Starkane`
- `SafeSwap`
- `SocialSphere`
Can I work on this topic?  

Feel free to check out my OnlyDust profile, where I have contributed to many projects: [OnlyDust Profile](https://app.onlydust.com/u/SimplementeCao),  
and my [GitHub profile](https://github.com/SimplementeCao).

---

### 🛠️ Plan to solve the problem:

1. **Review the problem description** to ensure a complete understanding of the problem at hand.  
2. **Take advantage of all available resources** provided within the problem to gain deeper insights.  
3. If faced with a problem, **I will promptly **ask questions** in the relevant support group or communication channel to move forward in an efficient manner.  
4. Once the problem is resolved, **I will submit a PR** and await your feedback.
---

Estimated time 10hs

---

Let me know if I can start working on this! 🚀

---

**Comment by od-hunter** [comment] 2024-12-14 03:07
Hi, please can I be assigned this please? This would be my first time contributing to this project and I'd love to be the given the opportunity to solve this issue please. I have experience in html, css, JavaScript, TypeScript and cairo

I'll take the following steps in solving this issue:
1. First, I'll use the React Icons library to identify equivalent icons for Icon.svg, icon1.jpg, and icon2.jpg.
2. Then I'll now replace <img> tags with React Icon components such as icon.svg to replace in PasswordHeader.tsx and ForgotPasswordCard.tsx, icon1.jpg to replace in ProcessTimeline/index.tsx with an appropriate React Icon and icon2.jpg to replace in ProcessTimeline/index.tsx with another React Icon.
3. Next, I'll use css to style the icons to match the original image dimensions and colors.
4. Lastly, I'll test to validate component behavior and to verify visual consistency, responsiveness, and accessibility.

Kindly assign me please, I'm up for the task.

**Comment by BigBen-7** [comment] 2024-12-14 03:33
Hey, I specialize in using React and its sub-library like eact-icons, can I attend to this issue?
ETA; 3hours max

**Comment by wheval** [comment] 2024-12-14 04:03
Hello @JosueBrenes, I'm Wheval an experienced Frontend Developer.

I'd love to give this a go. I have gone through the migration details, pretty straightfoward.

ETA is 5hrs.

**Closed** 2024-12-23 13:58 UTC
Labels: good first issue, External contributors, Maintainer -  Anwar, ODHack11, Unpaid/Not Rewarded
